### ISSUE TITLE
[Android] Crash after few seconds of running

### ISSUE THREAD

**Issue by piotr-andrychiewicz-spaceos** [smartlook/smartlook-mobile-issue-tracker#131] opened 2022-01-17 12:20 UTC
**Platform**
Android

**Technology**
Native

**Affected devices [optional]**
All

**Smartlook SDK version**
1.8.9-native

**Summary**
Application crash after few seconds of run. The error is like following:
`2022-01-17 12:46:52.018 20407-20407/io.spaceos.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.spaceos.demo, PID: 20407
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/WorkQuery$Builder;
        at com.smartlook.nc.h(SourceFile:7)
        at com.smartlook.nc.b(SourceFile:8)
        at com.smartlook.nc.a(SourceFile:14)
        at com.smartlook.cc.a(SourceFile:16)
        at com.smartlook.i9.a(SourceFile:76)
        at com.smartlook.i9.a(SourceFile:25)
        at com.smartlook.i9.e(SourceFile:33)
        at com.smartlook.i9.d(SourceFile:546)
        at com.smartlook.i9.f(SourceFile:13)
        at com.smartlook.aa.a(SourceFile:88)
        at com.smartlook.aa.b(SourceFile:51)
        at com.smartlook.aa.a(SourceFile:51)
        at com.smartlook.aa.c(SourceFile:19)
        at com.smartlook.aa.k(SourceFile:14)
        at com.smartlook.aa.g(SourceFile:1)
        at com.smartlook.aa$g.c(SourceFile:23)
        at com.smartlook.z8$m.a(SourceFile:1)
        at com.smartlook.z8$m.invoke(SourceFile:1)
        at com.smartlook.y8.a(SourceFile:200)
        at com.smartlook.y8.a(SourceFile:3)
        at com.smartlook.z8.d(SourceFile:15)
        at com.smartlook.b8.k(SourceFile:3)
        at com.smartlook.b8.b(SourceFile:3)
        at com.smartlook.sdk.smartlook.SmartlookBase.setupAndStartRecording(SourceFile:9)
        at io.upnext.wms.ui.main.MainActivity.setupSmartLookSdk(MainActivity.kt:183)
        at io.upnext.wms.ui.main.MainActivity.onCreate(MainActivity.kt:168)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.WorkQuery$Builder" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/io.spaceos.demo-1eqrlRzPTAHu1u7M1Ds0VQ==/base.apk"],nativeLibraryDirectories=[/data/app/io.spaceos.demo-1eqrlRzPTAHu1u7M1Ds0VQ==/lib/arm, /data/app/io.spaceos.demo-1eqrlRzPTAHu1u7M1Ds0VQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.smartlook.nc.h(SourceFile:7) 
        at com.smartlook.nc.b(SourceFile:8) 
        at com.smartlook.nc.a(SourceFile:14) 
        at com.smartlook.cc.a(SourceFile:16) 
        at com.smartlook.i9.a(SourceFile:76) 
        at com.smartlook.i9.a(SourceFile:25) 
        at com.smartlook.i9.e(SourceFile:33) 
        at com.smartlook.i9.d(SourceFile:546) 
        at com.smartlook.i9.f(SourceFile:13) 
        at com.smartlook.aa.a(SourceFile:88) 
        at com.smartlook.aa.b(SourceFile:51) 
        at com.smartlook.aa.a(SourceFile:51) 
        at com.smartlook.aa.c(SourceFile:19) 
        at com.smartlook.aa.k(SourceFile:14) 
        at com.smartlook.aa.g(SourceFile:1) 
        at com.smartlook.aa$g.c(SourceFile:23) 
        at com.smartlook.z8$m.a(SourceFile:1) 
        at com.smartlook.z8$m.invoke(SourceFile:1) 
        at com.smartlook.y8.a(SourceFile:200) 
        at com.smartlook.y8.a(SourceFile:3) 
        at com.smartlook.z8.d(SourceFile:15) 
        at com.smartlook.b8.k(SourceFile:3) 
        at com.smartlook.b8.b(SourceFile:3) 
        at com.smartlook.sdk.smartlook.SmartlookBase.setupAndStartRecording(SourceFile:9) 
        at io.upnext.wms.ui.main.MainActivity.setupSmartLookSdk(MainActivity.kt:183) 
        at io.upnext.wms.ui.main.MainActivity.onCreate(MainActivity.kt:168) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) `

I seems like SDK i trying to use WorkManager API however when I print dependencies for the library there is no dependency on androidx related package, there is only dependency to kotlin-stdlib:
+--- com.smartlook.recording:app:{prefer 1.8.9-native} -> 1.8.9-native
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10 -> 1.6.10 (*)
Application is integrated to start recording on MainActivity using the code provided in documentation. After few seconds of usage it crashes.
I've integrated SDK also on clean sample project, dependencies looks the same but there is no crash. Do you know what might be causing this behaviour?

**Comment by SenNeonoveNoci** [comment] 2022-01-18 15:06
Hello @piotr-andrychiewicz-spaceos,

thanks for your report we will look into this and keep you updated.

_František Spurný
Android developer_

**Comment by OndrejSynakSL** [comment] 2022-01-18 15:26
Hello, @piotr-andrychiewicz-spaceos,
Could you please share your Gradle file with us so we can check the dependencies you have in the project and reproduce the cause on our side? Thanks a lot

Ondrej Synak
Android developer

**Comment by SenNeonoveNoci** [comment] 2022-01-30 15:49
@piotr-andrychiewicz-spaceos We are removing `WorkManager` from our SDK in the next release (start of the next week). Thus this issue will be fixed. I'm closing this ticket.

**Closed by SenNeonoveNoci** 2022-01-30 15:49 UTC
Labels: bug, Android
