### ISSUE TITLE
Crashes after adding SmartLook SDK

### ISSUE THREAD

**Issue by seshuvinay** [smartlook/smartlook-mobile-issue-tracker#29] opened 2020-10-30 04:20 UTC
**Platform**
Android

**Technology**
native Android 

**Rendering [optional]**

**Affected devices [optional]**
 No pattern 

**Smartlook SDK version**
 1.6.0 native

**Summary**
We are getting crashes reported in Crashlytics after adding SmartLook SDK. Please find stacktraces below. 

**Steps to reproduce [optional]**
There is no particular pattern. We are unable to reproduce. But we are getting these reported from significant number of users

**Example Project [optional]**

**Relevant logs and/or screenshots**

Crash 1:

Fatal Exception: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
       at android.view.InputChannel.nativeReadFromParcel(InputChannel.java)
       at android.view.InputChannel.readFromParcel(InputChannel.java:148)
       at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:841)
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:662)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:344)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
       at android.widget.PopupWindow.invokePopup(PopupWindow.java:1380)
       at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1156)
       at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1119)
       at android.widget.Editor$AnimatePopupWindow.showAtLocation(Editor.java:3104)
       at android.widget.Editor$HandleView.updatePosition(Editor.java:4623)
       at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2570)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2245)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6399)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
       at android.view.Choreographer.doCallbacks(Choreographer.java:685)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6375)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

Crash 2:

Fatal Exception: kotlin.KotlinNullPointerException
       at a.b.a.a.e.i.g.b.a(b.java:305)
       at a.b.a.a.e.i.g.f.b.dispatchTouchEvent(b.java:1)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:692)
       at android.view.View.dispatchPointerEvent(View.java:13721)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6200)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5978)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5605)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5662)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5446)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5427)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8504)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8424)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8377)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8619)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:181)
       at android.app.ActivityThread.main(ActivityThread.java:7156)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

Crash 3:
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:729)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1348)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
       at a.b.a.a.f.d.c.a(c.java:1)
       at a.b.a.a.f.d.a.a(a.java:11)
       at a.b.a.a.f.b.a(b.java:8)
       at a.b.a.a.f.e.b.b(b.java:13)
       at a.b.a.a.f.e.b.d(b.java:1)
       at a.b.a.a.f.e.b.a(b.java:22)
       at a.b.a.a.f.e.b.a(b.java:2)
       at a.b.a.a.f.e.b$b.a(b.java:7)
       at a.b.a.a.f.e.b$b.a(b.java:1)
       at a.b.a.a.f.a.a(a.java:3)
       at a.b.a.a.f.a.a(a.java:1)
       at a.b.a.a.f.b$c.a(b.java:2)
       at a.b.a.a.f.d.a$b$c.run(a.java:1)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6375)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by SenNeonoveNoci** [comment] 2020-10-30 09:43
Hello @seshuvinay,
ad 1. I'm not sure if this issue is tied to Smartlook because I cannot see any link from this stack trace to our library.

ad 2. We are really sorry for this crash, there is apparently a bug in `1.6.0` version, please **update to** `1.6.2`.

ad 3. This s is a tricky one. We have internal ANR detection in our SDK so we are visible in all ANR stack traces. This does not mean we are causing the crash, we are just intercepting it. If you want to disable this behaviour of Smartlook SDK feel free to call:
```
Smartlook.setCrashTrackingMode(CrashTrackingMode.DISABLE);
```
on SDK setup.

**Comment by jeffreybenabou** [comment] 2020-10-30 11:23
same problem in my app, after updating to 1.6.2. its work fine

**Comment by SenNeonoveNoci** [comment] 2020-10-30 11:29
@jeffreybenabou Thanks for the message! We cannot reproduce the issue locally so we were waiting for someone to ensure us `1.6.2` works, thanks for that. We are updating docs right now.

**Comment by SenNeonoveNoci** [comment] 2020-10-30 12:34
@seshuvinay To follow up on 3rd crash, Is this happening on a specific device? Please provide as much additional info as possible.

**Comment by seshuvinay** [comment] 2020-10-31 03:21
All devices reported the 3rd crash so far are running Android 7. Not any specific device though.

**Comment by SenNeonoveNoci** [comment] 2020-11-02 10:06
@seshuvinay Can you reproduce this issue locally on your application?

**Comment by SenNeonoveNoci** [comment] 2020-11-23 09:15
Creator abandoned the issue. Closing.

**Closed by SenNeonoveNoci** 2020-11-23 09:15 UTC
Labels: Android, bug
