### ISSUE TITLE
iOS application seems to be crashed when i pass the custom properties with the custom event

### ISSUE THREAD

**Issue by Muzzamil75** [smartlook/smartlook-mobile-issue-tracker#143] opened 2022-03-10 12:37 UTC
**Platform**
iOS

**Technology**
React-native: 0.64.2

**Smartlook SDK version**
smartlook-react-native-wrapper 1.2.5

**Steps to reproduce **
Using TrackCustomEvent with custom properties causes the app to crash on iOS (without the custom props it works fine but when we add any custom parameter it crashes on iOS).

i.e  Smartlook.trackCustomEvent(‘Dashboard’, {name:’jack’})       // crash
      Smartlook.trackCustomEvent(‘Dashboard’)                              // works well 

**Relevant logs and/or screenshots**
No logs, Just the application closes on calling it

@krystofcelba Can you please look upon it.

**Comment by krystofcelba** [comment] 2022-03-11 09:44
Hey @Muzzamil75,
I see that you have changed the code which is crashing for you to the parameter as a string. In that case, I'm not able to reproduce it as it works fine to me with string values. Could you please run your app in Xcode and send me a crash log from it?

Thanks!

**Comment by Muzzamil75** [comment] 2022-03-14 09:06
@krystofcelba Yes with the string parameter it seems to work for iOS too. What about the parameter as a number? Are you going to fix or deal with it also ? to avoid the iOS crash?

**Comment by krystofcelba** [comment] 2022-05-02 07:45
Hey @Muzzamil75,
could you please update to v1.2.6? It should be fixed there.

**Comment by SenNeonoveNoci** [comment] 2022-05-26 13:45
@Muzzamil75 We are closing our GitHub issues and migrating all issue resolving to Intercom. If you have any further issues please write a follow up on **support@smartlook.com**.

**Closed by SenNeonoveNoci** 2022-05-26 13:45 UTC
Labels: bug, iOS, React native
