### ISSUE TITLE
Smartlook Snapshot Renderer causing crashes on iOS

### ISSUE THREAD

**Issue by paulcarpenter** [smartlook/smartlook-mobile-issue-tracker#82] opened 2021-05-17 00:13 UTC
**Platform**
iOS

**Technology**
Native / Swift / SwiftUI

**Affected devices [optional]**
iOS 14.4-14.6 beta

**Smartlook SDK version**
1.7.5

**Summary**
Our Crashlytics integration is reporting intermittent crashes attributed to `SLNativeSnapshotRenderer.m:408` with the message `-[NSConcreteValue doubleValue]: unrecognized selector sent to instance`

**Steps to reproduce [optional]**
Unknown.

**Comment by pavel-kroh-smartlook** [comment] 2021-05-17 07:20
Hi @paulcarpenter , thanks for the report. 

First, please check if this is a duplicate of https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/79 , which is solved in our latest release.

If not, please provide full stack-trace of the crash and detailed description under which circumstances it happens. The crash is most likely caused by the app setting an animation attribute to a value of wrong type. In order to work it around (if this is not solvable in the app itself, because the culprit is in some system or 3rd party component) we need to understand when exactly it happens.

Thanks.

**Comment by pavel-kroh-smartlook** [comment] 2021-05-26 08:48
Stalled and probably solved issue.

**Closed by pavel-kroh-smartlook** 2021-05-26 08:48 UTC
Labels: bug, iOS
