### ISSUE TITLE
issue while recording video

### ISSUE THREAD

**Issue by Vijay-KumarB** [smartlook/smartlook-mobile-issue-tracker#5] opened 2020-09-07 06:15 UTC
**Platform**

iOS

**Technology**

Cocos, Swift

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

3.8.2
**Summary**

We are using smartlook SDK in one of our applications and we are facing one issue. When we start recording video it works fine. When we navigate to screen where we have used AVFoundation for audio recording the app gets crashed. Suppose if we stop recording before navigating to audio recording screen it works fine. 

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

There is some issue with the recording and the error message is as follows:
2020-08-27 10:47:44.658473+0530 YiChi[67749:2039484] -[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x6000001b0780
2020-08-27 10:47:44.715945+0530 YiChi[67749:2039484] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x6000001b0780'

**Comment by pavel-kroh-smartlook** [comment] 2020-09-07 07:39
Hi, we will look into it asap. It would help us if you could provide the full stacktrace of the crashed method, where we will hopefully see the Smartlook method that causes it. Thanks.

**Comment by Vijay-KumarB** [comment] 2020-09-07 08:29
2020-09-07 13:58:55.745502+0530 YiChi[8237:148461] -[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x600001229900
2020-09-07 13:58:55.810332+0530 YiChi[8237:148461] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x600001229900'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5eb94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e4286c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e44b58 _CF_forwarding_prep_0 + 120
	5   QuartzCore                          0x00007fff2b57775c CAObject_setValueForKeyPath_ + 3470
	6   QuartzCore                          0x00007fff2b4e224e -[CALayer setValue:forKeyPath:] + 432
	7   QuartzCore                          0x00007fff2b52cce2 -[CABasicAnimation applyForTime:presentationObject:modelObject:] + 869
	8   QuartzCore                          0x00007fff2b5297e0 -[CAAnimationGroup applyForTime:presentationObject:modelObject:] + 205
	9   QuartzCore                          0x00007fff2b4f089e _ZN2CA5Layer18presentation_layerEPNS_11TransactionE + 644
	10  YiChi                               0x0000000109aca234 __37+[SLChangesDetector hasBeenAnimating]_block_invoke + 32
	11  CoreFoundation                      0x00007fff23d68d37 __NSSET_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	12  CoreFoundation                      0x00007fff23dad3ef -[__NSSetM enumerateObjectsWithOptions:usingBlock:] + 239
	13  YiChi                               0x0000000109aca1bf +[SLChangesDetector hasBeenAnimating] + 141
	14  YiChi                               0x0000000109a8c66e -[SLSnapshotTicker displayLinkTick:] + 968
	15  QuartzCore                          0x00007fff2b3a4186 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 538
	16  QuartzCore                          0x00007fff2b47b768 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 299
	17  CoreFoundation                      0x00007fff23d627dd __CFMachPortPerform + 157
	18  CoreFoundation                      0x00007fff23da2449 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	19  CoreFoundation                      0x00007fff23da1a48 __CFRunLoopDoSource1 + 472
	20  CoreFoundation                      0x00007fff23d9c474 __CFRunLoopRun + 2228
	21  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	22  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	23  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	24  YiChi                               0x0000000109562fbb main + 75
	25  libdyld.dylib                       0x00007fff520ce1fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pavel-kroh-smartlook** [comment] 2020-09-08 07:40
Hi again, the issue does not directly relates to the audio recording, but to some UI animations that go on when you navigate in the app that probably interfere with some things in our UI changes detection mechanism. We are now figuring out the best way how to fix it.

**Comment by Vijay-KumarB** [comment] 2020-09-09 11:23
Sure we will wait for the update

**Comment by pavel-kroh-smartlook** [comment] 2020-10-06 07:18
Hi, we have just released a new version (1.5.0) where we try to fix this problem. As we cannot it reproduce, we refactored the related code to be more thread safe (which we think could be the cause of the issue).

**Comment by Vijay-KumarB** [comment] 2020-10-08 17:27
Even after using version 1.5.0 we are facing the same issue

**Comment by pavel-kroh-smartlook** [comment] 2020-10-08 18:26
Damn... thank you so much for trying it, we are sorry the update did not help. Will look into it in depth again.

**Comment by jCharv** [comment] 2020-10-23 08:39
Hey @Vijay-KumarB . I've looked into this issue a bit, but I can't see any problem in our SDK. My theory would be that you have some animation (CABasicAnimation or a derivative of it) on that screen you mentioned. That animation might have incorrect values assigned to fromValue or toValue, like in this example https://stackoverflow.com/a/51377378 . Most likely this animation is not triggered in your code, but our SDK triggers it, which causes the crash. Just a theory, but imo it's worth a look.

**Comment by pavel-kroh-smartlook** [comment] 2020-10-23 09:00
I would just add that we do not really trigger animations, but we access them in order to test if there are some ongoing changes on the screen we should capture. This may cause the incorrect NSValue type being evaluated which in turn causes the crash.

**Comment by pavel-kroh-smartlook** [comment] 2020-11-10 13:21
Closed due to inactivity.

**Closed by pavel-kroh-smartlook** 2020-11-10 13:21 UTC
Labels: Cocos, bug, iOS

**Comment by roimulia2** [comment] 2021-08-24 10:13
Hey there,

We are having the same issue now:
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x280a01650'
`

Currently, we won't integrate SmartLook as it's too risky. The good thing is that we are available for a debugging session if that will help you in anyway :)

**Comment by roimulia2** [comment] 2021-08-24 10:15
Also, worth noticing that it's been triggered when navigating to a screen with AVFoundation logic.

**Comment by pavel-kroh-smartlook** [comment] 2021-08-24 10:19
Hi @roimulia2 , what version of Smartlook do you use?

**Comment by roimulia2** [comment] 2021-08-24 10:20
@pavel-kroh-smartlook  1.7.9

**Comment by pavel-kroh-smartlook** [comment] 2021-08-24 14:31
Thanks… we look into it, apparently we do not workaround all the corrupted animations…

**Comment by roimulia2** [comment] 2021-08-25 06:41
@pavel-kroh-smartlook Sure! Should I expect a quick fix? What's the plan?
