### ISSUE TITLE
Smartlook.unregisterBlacklistedView not working on android

### ISSUE THREAD

**Issue by JehuReynoso** [smartlook/smartlook-mobile-issue-tracker#49] opened 2021-01-11 21:15 UTC
**Platform**
Android

**Technology**
React native

**Smartlook SDK version**
1.6.3-react

I have problems when trying to record a webview in android, in iOS is working perfeclty, but in Android the video recorded is still blacked...

Also the Smartlook.stopRecording(); function seems not working on android, i need to close the app in order to stop recording.

```
const _onLoadWebView = () => {
    const options = {};
    options.smartlookAPIKey = smartlookSdkConfig.sdkKey;
    options.startNewSessionAndUser = true;
    Smartlook.setup(options);
    Smartlook.setUserIdentifier("creditUpsell");
    Smartlook.unregisterBlacklistedView(webViewRef.current);
    setTimeout(function() {
      Smartlook.startRecording();
    }, 2500);
  }

........

<WebView
      ref={webViewRef}
      domStorageEnabled={true}
      startInLoadingState={true}
      javaScriptEnabledAndroid={true}
      useWebKit={true}
      source={{
        uri
      }}
      onLoad={_onLoadWebView}
      onMessage={_onMessageReceived}
      onError={_handleWebViewError}
      onHttpError={_handleWebViewError}
      renderError={() => <View />}
    />
```

**Comment by SenNeonoveNoci** [comment] 2021-01-12 13:07
Closed because its duplicate of [!50](https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/50)

**Closed by SenNeonoveNoci** 2021-01-12 13:07 UTC
Labels: bug
