### ISSUE TITLE
Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')

### ISSUE THREAD

**Issue by Kondamon** [smartlook/smartlook-mobile-issue-tracker#83] opened 2021-05-31 07:14 UTC
**Platform**

iOS

**Technology**

native

**Smartlook SDK version**

1.7.6

**Summary**

Smartlook 1.7.6 was build with Xcode 12.5. With Xcode 12.4 the latest version 1.7.6 can not be used anymore because you reveive an archive error: ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')',

**Steps to reproduce [optional]**
1. Install Xcode 12.4
2. Add smartlook framework
3. Archive product

**Question**
Is it inevitable that smartlook 1.7.6 has to be build with Xcode 12.5? At the moment there are still some bugs in XCode 12.5 or Big Sur that prevents me from switching to it. Therefore I have to downgrade to Smartlook 1.7.5.

**Comment by pavel-kroh-smartlook** [comment] 2021-05-31 07:21
Hi @Kondamon , how do you embed Smartlook? Directly, via Cocoapods or Swift package?

**Comment by Kondamon** [comment] 2021-05-31 07:43
Hi @pavel-kroh-smartlook, thanks for your quick reply. Via Swift package manager.

**Comment by pavel-kroh-smartlook** [comment] 2021-05-31 07:59
I see. 

Thanks @Kondamon for reporting, we will look into it and make sure the released frameworks are (better) compatible across Xcode versions. 

It seems that Xcode 12.5 introduced some breaking changes into the bitcode. We already got one similar report via a private channel, but they use a rare combination for a really old Xcode and Cocoapods, and it worked with Swift Packages in their case. We run some tests with various combinations of Xcode versions and it seemed that the issue is quite isolated to their environment… but apparently there are more circumstances when this happen.

**Comment by Kondamon** [comment] 2021-05-31 09:58
Thank you, @pavel-kroh-smartlook!

**Comment by paxful-ios** [comment] 2021-06-28 11:48
Hey @pavel-kroh-smartlook 
We also faced this error, any updates or workaround here?

**Comment by pavel-kroh-smartlook** [comment] 2021-06-29 07:39
Jo @paxful-ios , we communicated about it with Apple a bit and found a workaround. We prepared a new SDK build compiled in an older version of Xcode, and we will have to do it for some time till new compiler version is widely adopted. 

The backward bitwise-compatible version is released in Cocoapods as version 1.7.6.1 (the same as 1.7.6, just recompiled). If you embed Smartlook directly, the download link is here: https://sdk.smartlook.com/ios/smartlook-ios-sdk-1.7.6.1.3345.zip

**Comment by paxful-ios** [comment] 2021-06-29 08:55
Thank you for your reply @pavel-kroh-smartlook 
Is there any possibility to embed Smartlook via SPM?

**Comment by pavel-kroh-smartlook** [comment] 2021-06-29 10:34
@paxful-ios , indeed, but I see there is still the bitcode incompatible version. I'll update it soon and let you know… 

https://github.com/smartlook/SmartlookSwiftPackage

**Comment by pavel-kroh-smartlook** [comment] 2021-07-03 09:17
Hi @paxful-ios , the Swift Package has been updated to the bitcode back-compatible version 1.7.7, too.

**Comment by SudhirGadhvi** [comment] 2021-07-10 06:53
Still facing the issue
Xcode: 12.5.1
Smartlook SDK version: 1.7.7

Swift Package Manager

Error:
(Smartlook-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.


Xcode setting -> ENABLE_BITCODE is set to true already.

**Comment by pavel-kroh-smartlook** [comment] 2021-07-13 05:52
Hi @SudhirGadhvi  , thanks for detailed report! It looks like a bug in the package, sorry for the inconvenience. I'll look into it immediately.

**Comment by pavel-kroh-smartlook** [comment] 2021-07-13 07:19
Hi @SudhirGadhvi , please update the SwiftPackage to the latest version (1.7.8). The issue is solved there.

**Comment by SudhirGadhvi** [comment] 2021-07-14 05:52
@pavel-kroh-smartlook: Thanks for the quick response. It's working now, Thank you :)

**Comment by pavel-kroh-smartlook** [comment] 2021-07-14 06:28
@SudhirGadhvi thanks for confirming! Cheers.

**Comment by pavel-kroh-smartlook** [comment] 2021-11-01 13:57
@papmodern : there a backaward compatibility issue in our Flutter plugin which now requires Xcode 13.

There are two possible solutions:
- upgrade Xcode on your side (Xcode 13 is the production version of Xcode, no beta)
- wait few days for us releasing a plugin with backward-compatible Smartlook binary

**Comment by pavel-kroh-smartlook** [comment] 2021-11-05 07:33
Hi all, new version of Smartlook Flutter plugin has been released, with backward-compatible native code: https://pub.dev/packages/flutter_smartlook

**Closed by pavel-kroh-smartlook** 2021-11-05 07:33 UTC
Labels: bug, iOS, Flutter

**Comment by papmodern** [comment] 2021-11-06 14:58
I'm still getting the error in the latest version with xcode 12.5.1
