### ISSUE TITLE
Compiler error due to architecture arm64 

### ISSUE THREAD

**Issue by Hossam-Hawary** [smartlook/smartlook-mobile-issue-tracker#89] opened 2021-07-12 20:59 UTC
**Platform**

IOS

**Technology**
Ionic 4

**Build instructions [optional]**

MacOS 11.4

Xcode
Version 12.5.1 (12E507)
--------------------------------
`gem -v cocoapods `

**2.7.6.2**
--------------------------------
`ionic -v`
                                                                                                                                 
** 5.4.16**
--------------------------------
`cordova -v`

**10.0.0**
--------------------------------
 **"cordova-ios": "6.2.0"**
--------------------------------
Podfile

```
source 'https://cdn.cocoapods.org/'
platform :ios, '14.5'
use_frameworks!
target 'كرتونة' do
	project '#####.xcodeproj'
	pod 'CleverTap-iOS-SDK', '3.9.4'
	pod 'AppsFlyerFramework', '6.3.2'
	pod 'Smartlook', '>= 1.7.6.1'
	pod 'Intercom', '~> 10.0.1'
	pod 'Firebase/Messaging', '~> 7.4.0'
end

```

**Smartlook SDK version**

  "cordova-plugin-smartlook": "^1.7.4"
   "@ionic-native/smartlook": "^5.34.0"
   pod 'Smartlook', '>= 1.7.6.1'

**Summary**

I'm not able to build IOS due to this error below regarding the arm64 
Note: I already tried many times to exclude the arm64 from any IOS simulator SDK but didn't work 

```

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/cmqtuyqvbeahxegikkspeteaqqft/Build/Intermediates.noindex/ArchiveIntermediates/كرتونة/IntermediateBuildFilesPath/PROJECT.build/Debug-iphoneos/PROJECT.build/Objects-normal/arm64/SmartlookPlugin.o /app/platforms/ios/PROJECT/Plugins/cordova-plugin-smartlook/SmartlookPlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
```

<img width="1523" alt="Screen Shot 2021-07-12 at 10 49 32 PM" src="https://user-images.githubusercontent.com/17249951/125354133-bb629680-e363-11eb-8f02-2f7afe48fc28.png">
<img width="1268" alt="Screen Shot 2021-07-12 at 10 50 30 PM" src="https://user-images.githubusercontent.com/17249951/125354149-c1587780-e363-11eb-94c1-999372d13152.png">
<img width="1792" alt="Screen Shot 2021-07-12 at 10 53 37 PM" src="https://user-images.githubusercontent.com/17249951/125354583-417edd00-e364-11eb-903a-56bb51afbd5d.png">

**Comment by pavel-kroh-smartlook** [comment] 2021-07-13 05:51
Hi @Hossam-Hawary , thanks for detailed report! It looks like a bug in the package, sorry for the inconvenience. I'll look into it immediately.

**Comment by pavel-kroh-smartlook** [comment] 2021-07-13 09:03
Hi @Hossam-Hawary , 

upon closer inspection, there is no issue with the Smartlook package.

This looks more like a caching issue.

Please try the following steps:
1. **do not exclude any architecture**
2. in terminal, run this command to clean Cocoapods caches `pod cache clean --all`
3. in Xcode, clean build folder from menu `Product` → `Clean Build Folder`
4. eventually, remove also Xcode cache (delete `~/Library/Developer/Xcode/DerivedData` folder)

Then try rebuilding the project.

**Comment by Hossam-Hawary** [comment] 2021-07-14 12:27
Hi @pavel-kroh-smartlook, thank you for your quick response

Actually, I already clean the cache almost with every build 
I'm stuck on it for a couple of days so far and still, so I would really appreciate any help from your side

**Comment by krystofcelba** [comment] 2021-07-15 01:52
Hey @Hossam-Hawary,
Firstly, could you please check if you have set a valid provisioning profile in your project? There is a good guide on how to do it in this answer at StackOverflow https://stackoverflow.com/a/44102979/2826077.

If it will not help, please try to run these commands to do a completely fresh build.

```
rm -rf node_modules
rm -rf platform
npm i
ionic cordova platform add ios
ionic cordova prepare ios
ionic cordova build ios --prod
```

**Comment by pavel-kroh-smartlook** [comment] 2021-07-26 07:17
Hi again, this issue could be also caused by older version of Cocoapods that are used to build the app.

**Comment by Hossam-Hawary** [comment] 2021-07-26 13:27
@pavel-kroh-smartlook as I mentioned above I use the **Cocoapods** version **2.7.6.2** and I think it's the latest version

**Comment by pavel-kroh-smartlook** [comment] 2021-07-26 17:30
@Hossam-Hawary this must be some misunderstanding, the lates Cocoapods (the package distribution framework) release is `1.10.1`  https://github.com/CocoaPods/CocoaPods/releases

**Comment by pavel-kroh-smartlook** [comment] 2021-08-09 15:43
Closing abandoned issue.

**Closed by pavel-kroh-smartlook** 2021-08-09 15:43 UTC
Labels: bug, iOS
